### ISSUE TITLE
后续开发任务

### ISSUE THREAD

**Issue by CodeToSurvive1** [CodeToSurvive1/reliable-master#1]
1.业务系统发起任务或者创建job，调用master创建任务job，master需要提供接口
2.job开始的时候 ，slave通知master job开始 ，该功能已经存在 ，但是需要添加逻辑-> master需要调用通知相关业务系统job开始 
3.job结束的时候  slave也要通知mater，目前只返回状态跟步骤日志 ，但是截图信息没有处理返回，后续需要添加截图封装或者结果打包返回给master，  master返回给业务系统
4.master分发任务需要根据任务所指定的设备，对应分发到连接有该设备的slave     
5.npm install 修改实现方式
6.git clone能否支持webservice接口方式，比如脚本跟应用可以通过业务系统下载方式
7.编写脚本公共指令分装，公共部分提取出来，测试人员只需要编写具体的操作逻辑，驱动初始化，退出进行封装，不需要测试人员再编写
8.脚本录制器 
9.页面脚本编辑器，简单的直接textarea

**Comment by CodeToSurvive1** [comment]
1.业务系统发起任务或者创建job，调用master创建任务job，master需要提供接口[ok]      
curl -d "repositoryUrl=https://github.com/CodeToSurvive1/bank_sample.git&repositoryBranch=dev&serialNumber=DU2MYN146D002912" http://localhost:3333/api/matc/jobs/add

3.job结束的时候 slave也要通知mater，目前只返回状态跟步骤日志 ，但是截图信息没有处理返回，后续需要添加截图封装或者结果打包返回给master， master返回给业务系统[ok]    

curl -F "filename=@/Users/mac/Desktop/111222333.zip" http://localhost:3333/api/matc/result

4.master分发任务需要根据任务所指定的设备，对应分发到连接有该设备的slave,任务开始锁定设备，任务结束解锁设备[ok]

**Comment by CodeToSurvive1** [comment]
任务分配：       
 @xiaomingstudy  1跟2     
@SmallBlackboard   3跟4
1.创建任务的时候添加脚本url，apkurl，状态通知url，结果返回url，并在master接受任务的时候根据是否存在apk(md5)算法决定是否去业务系统下载apk，同时返回taskid或者jobid   12月14日    
2.修改现有的状态通知接口，结果返回接口 (目前在配置文件中)，需要根据1中的传过来的接口进行通知状态   12月16日    
3.修改npm install方式为webservice方式，即通过1中的脚本url去业务系统中下载脚本，并进行公共代码的封装，这里修改require为全局方式，并添加相关的逻辑，比如校验码，比如apk没有变更等    12月16日 
4.macaca启动方式修改(并发问题)    12月16日

**Comment by shishy421** [comment]
1.数据库中新增project、app、script对应表attachment，master上下载app和脚本后，该表新增一条记录，记录app和脚本的保存路径，并将该条记录attachmentId发送给slave。---------OK
2.master增加接口，【slave请求该接口（参数：attachmentId）】，master接收attachmentId，将app、script文件响应给slave。---------OK
请求app文件 : http://192.168.155.1:3333/getAttachments/getApp/:attachmentId
请求app文件md5值 : http://192.168.155.1:3333/getAttachments/getApp/:attachmentId?checkmd5=true
请求script文件 : http://192.168.155.1:3333/getAttachments/getScript/:attachmentId
请求script文件md5值 : http://192.168.155.1:3333/getAttachments/getScript/:attachmentId?checkmd5=true

**Comment by xiaomingstudy** [comment]
更改业务系统解析压缩包方式以及数据库的存储

**Comment by shishy421** [comment]
macaca启动方式修改(并发问题)
修改依赖文件：macaca-cli/lib/run/index.js
行号26-34改为：
Runner.prototype.init = function(options) {
  this.options = options;
  if (!global.serverFlag) {
      global.serverFlag = true;
    this.startServer();
  } else {
    this.initFramework();
  }
};
行号102-108改为：
module.exports = function(options) {
   //if (!runner) {
    runner = new Runner();
   //}
  runner.removeAllListeners();
  runner.init(options);
  return runner;
};

**Comment by CodeToSurvive1** [comment]
已经ok
